### ISSUE TITLE
该怎么添加对steam验证码的支持？

### ISSUE THREAD

**Issue by alexcdever** [zzyandzzy/captcha#1]
如题，自定义规则看不出规律，想照猫画虎一波也做不到。。

**Comment by zzyandzzy** [comment]
https://github.com/zzyandzzy/captcha/blob/master/app/src/main/java/com/zzy/captcha/utils/CopyCaptchaUtila.java
可以看看这个源码，有些乱，寒假写的，现在都没时间维护了。
